# Generated by Django 5.1.6 on 2025-02-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='identifier',
            unique_together={('user', 'type')},
        ),
    ]
