# Generated by Django 5.2.6 on 2025-10-01 04:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='REQUESTED', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('previous_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('new_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
