# Generated by Django 5.1.6 on 2025-02-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=50)),
                ('previous_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('new_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
