# Generated by Django 5.2.6 on 2025-10-01 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='rescheduled_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='events.baseevent'),
        ),
        migrations.AddField(
            model_name='eventstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventstatushistory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='events.baseevent'),
        ),
        migrations.AddIndex(
            model_name='baseevent',
            index=models.Index(fields=['event_type', 'status'], name='events_base_event_t_67b60f_idx'),
        ),
        migrations.AddIndex(
            model_name='baseevent',
            index=models.Index(fields=['created_by', 'created_at'], name='events_base_created_0dd82b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstatushistory',
            index=models.Index(fields=['event_type', 'new_status', 'changed_at'], name='events_even_event_t_95127d_idx'),
        ),
    ]
