services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=bayleaf_db
      - DB_USER=dbuser
      - DB_PASSWORD=igrp2020
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bayleaf_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=igrp2020
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d bayleaf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: