# Generated by Django 5.2.7 on 2025-10-07 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0002_initial'),
        ('medications', '0002_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEDICATION', 'Medication'), ('APPOINTMENT', 'Appointment'), ('EDUCATION', 'Education'), ('MEASUREMENT', 'Measurement'), ('TASK', 'Task')], max_length=32)),
                ('instructions_richtext', models.TextField(blank=True, default='')),
                ('required_role', models.CharField(blank=True, default='', max_length=64)),
                ('schedule_json', models.JSONField(blank=True, default=dict)),
                ('completion_criteria_json', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_careplans', to='professionals.professional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careplans', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarePlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MEDICATION', 'Medication'), ('APPOINTMENT', 'Appointment'), ('EDUCATION', 'Education'), ('MEASUREMENT', 'Measurement'), ('TASK', 'Task')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=128)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('custom_instructions_richtext', models.TextField(blank=True, default='')),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_careplan_actions', to='professionals.professional')),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='careplans.careplan')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='careplans.actiontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentActionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_window_start', models.DateTimeField(blank=True, null=True)),
                ('preferred_window_end', models.DateTimeField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='professionals.specialization')),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_detail', to='careplans.careplanaction')),
            ],
        ),
        migrations.CreateModel(
            name='CarePlanActivityEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.baseevent')),
                ('scheduled_to', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='careplans.careplanaction')),
            ],
            options={
                'ordering': ['scheduled_to'],
                'abstract': False,
            },
            bases=('events.baseevent',),
        ),
        migrations.CreateModel(
            name='CarePlanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('CONTINUE', 'Continue'), ('ADJUST', 'Adjust'), ('STOP', 'Stop')], default='CONTINUE', max_length=16)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='careplans.careplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careplan_reviews', to='professionals.professional')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('is_published', models.BooleanField(default=False)),
                ('applicability_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_careplan_templates', to='professionals.professional')),
            ],
        ),
        migrations.AddField(
            model_name='careplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='careplans.careplantemplate'),
        ),
        migrations.AddField(
            model_name='actiontemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to='careplans.careplantemplate'),
        ),
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_metric_code', models.CharField(blank=True, default='', max_length=64)),
                ('target_value', models.JSONField(blank=True, default=dict)),
                ('timeframe_days', models.PositiveIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_templates', to='careplans.careplantemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CarePlanGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('target_metric_code', models.CharField(blank=True, default='', max_length=64)),
                ('target_value_json', models.JSONField(blank=True, default=dict)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('ACHIEVED', 'Achieved'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='careplans.careplan')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='careplans.goaltemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationActionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, default='', max_length=128)),
                ('route', models.CharField(blank=True, default='', max_length=64)),
                ('frequency', models.CharField(blank=True, default='', max_length=64)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_detail', to='careplans.careplanaction')),
                ('medication_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medications.medicationitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='careplanaction',
            index=models.Index(fields=['careplan', 'category', 'status'], name='careplans_c_carepla_8f388a_idx'),
        ),
        migrations.AddIndex(
            model_name='careplanaction',
            index=models.Index(fields=['category', 'status'], name='careplans_c_categor_1ffe0c_idx'),
        ),
        migrations.AddIndex(
            model_name='careplantemplate',
            index=models.Index(fields=['name', 'version'], name='careplans_c_name_4f0ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='careplantemplate',
            index=models.Index(fields=['is_published'], name='careplans_c_is_publ_ffaeef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careplantemplate',
            unique_together={('name', 'version')},
        ),
    ]
