# Generated by Django 5.2.7 on 2025-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careplanactivityevent',
            options={'ordering': ['due_from']},
        ),
        migrations.RenameField(
            model_name='careplanactivityevent',
            old_name='scheduled_to',
            new_name='due_from',
        ),
        migrations.RemoveField(
            model_name='careplanactivityevent',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='careplanactivityevent',
            name='due_until',
            field=models.DateTimeField(db_index=True),
            preserve_default=False,
        ),
    ]
