# Generated by Django 5.2.7 on 2025-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplans', '0002_alter_careplanactivityevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanaction',
            name='schedule_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='careplanactivityevent',
            name='due_from',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='careplanactivityevent',
            name='due_until',
            field=models.DateTimeField(db_index=True, default=None),
        ),
    ]
