# Generated by Django 5.2.6 on 2025-10-01 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medication Prescription',
                'verbose_name_plural': 'Medication Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='TakeMedicationEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.baseevent')),
                ('scheduled_to_complete_from', models.DateTimeField(db_index=True)),
                ('scheduled_to_complete_until', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Take Medication Event',
                'verbose_name_plural': 'Take Medication Events',
            },
            bases=('events.baseevent',),
        ),
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosage_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency_hours', models.PositiveIntegerField(help_text='Interval between doses, in hours.')),
                ('instructions', models.TextField(blank=True)),
                ('total_unit_amount', models.PositiveIntegerField(help_text='Total number of units (e.g., capsules, tablets) to be taken over the course.')),
                ('dosage_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dosageunit')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
