# Generated by Django 5.2.6 on 2025-10-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationitem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prescriptions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicationprescription',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prescriptions', to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_items', to='medications.medicationprescription'),
        ),
        migrations.AddField(
            model_name='takemedicationevent',
            name='medication_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_events', to='medications.medicationitem'),
        ),
    ]
