# Generated by Django 5.1.7 on 2025-04-02 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('patients', '0002_patient_avatar'),
        ('professionals', '0004_professional_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prescriptions', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prescriptions', to='professionals.professional')),
            ],
            options={
                'verbose_name': 'Medication Prescription',
                'verbose_name_plural': 'Medication Prescriptions',
            },
        ),
    ]
