# Generated by Django 5.1.7 on 2025-04-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dosageunit'),
        ('medications', '0002_medicationprescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency_hours', models.PositiveIntegerField(help_text='Interval between doses, in hours.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('dosage_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dosageunit')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_items', to='medications.medicationprescription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
