# Generated by Django 5.1.7 on 2025-04-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationitem',
            name='total_unit_amount',
            field=models.PositiveIntegerField(default=1, help_text='Total number of units (e.g., capsules, tablets) to be taken over the course.'),
            preserve_default=False,
        ),
    ]
