# Generated by Django 5.1.7 on 2025-04-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medicationitem_total_unit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationitem',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='medicationitem',
            name='start_date',
        ),
    ]
