# Generated by Django 5.1.7 on 2025-04-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_takemedicationevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takemedicationevent',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='takemedicationevent',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='takemedicationevent',
            name='medication_name',
        ),
    ]
