# Generated by Django 5.1.7 on 2025-04-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_remove_takemedicationevent_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takemedicationevent',
            name='patient',
        ),
    ]
