# Generated by Django 5.1.7 on 2025-09-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_remove_takemedicationevent_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takemedicationevent',
            name='prescription',
        ),
        migrations.AddField(
            model_name='takemedicationevent',
            name='medication_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_events', to='medications.medicationitem'),
        ),
        migrations.AlterField(
            model_name='medicationitem',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_items', to='medications.medicationprescription'),
        ),
    ]
