# Generated by Django 5.2.6 on 2025-09-19 23:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_remove_takemedicationevent_prescription_and_more'),
        ('patients', '0002_patient_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='patients.patient'),
            preserve_default=False,
        ),
    ]
