# Generated by Django 5.1.6 on 2025-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='core.service'),
        ),
        migrations.AddField(
            model_name='professional',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='professionals.specialization'),
        ),
    ]
