# Generated by Django 5.2.6 on 2026-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='core.organization'),
        ),
    ]
