# Generated by Django 5.1.6 on 2025-03-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='doctor',
            new_name='professional',
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('professional', 'weekday', 'service', 'from_time', 'to_time')},
        ),
    ]
