# Generated by Django 5.1.6 on 2025-03-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_specialization_professional_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
