# Generated by Django 5.2.6 on 2026-03-18 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_organization'),
        ('professionals', '0002_professional_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_key', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to='professionals.professional')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.organization')),
            ],
            options={
                'ordering': ['name', 'doc_key'],
                'constraints': [models.UniqueConstraint(fields=('org', 'doc_key'), name='uniq_document_org_doc_key')],
            },
        ),
    ]
