# Generated by Django 5.2.6 on 2026-02-21

import uuid
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_organization"),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFamily",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("doc_key", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("SOP", "SOP"),
                            ("MANUAL", "Manual"),
                            ("POLICY", "Policy"),
                            ("FORM", "Form"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_families",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "doc_key"],
                "constraints": [
                    models.UniqueConstraint(fields=("org", "doc_key"), name="uniq_document_family_org_doc_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_label", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("EFFECTIVE", "Effective"),
                            ("SUPERSEDED", "Superseded"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[("minio", "MinIO"), ("s3", "S3")],
                        default="minio",
                        max_length=16,
                    ),
                ),
                ("bucket", models.CharField(max_length=128)),
                ("object_key", models.CharField(max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "index_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("INDEXED", "Indexed"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("index_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions_created",
                        to="professionals.professional",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.documentfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "version_label"),
                        name="uniq_document_version_family_label",
                    ),
                    models.UniqueConstraint(
                        condition=Q(status="EFFECTIVE"),
                        fields=("family",),
                        name="uniq_effective_document_version_per_family",
                    ),
                ],
            },
        ),
    ]
