# Generated by Django 5.2.6 on 2026-02-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfamily",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_families",
                to="core.organization",
            ),
        ),
    ]
