# Generated by Django 5.2.6 on 2026-02-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_documentfamily_org_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentversion",
            name="index_error",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="index_status",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="indexed_at",
        ),
    ]
