# Generated by Django 5.1.6 on 2025-02-26 04:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], default='REQUESTED', max_length=20)),
                ('scheduled_to', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
