# Generated by Django 5.1.6 on 2025-02-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_at',
        ),
    ]
