# Generated by Django 5.1.7 on 2025-05-28 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_created_by'),
        ('professionals', '0005_serviceslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='shift',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='professionals.serviceslot'),
        ),
    ]
