# Generated by Django 5.1.6 on 2025-02-27 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL)),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lab.sampletype')),
            ],
        ),
        migrations.CreateModel(
            name='SampleStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=None, null=True)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_transitions', to='lab.samplestate')),
                ('previous_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_transitions', to='lab.samplestate')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='lab.sample')),
            ],
        ),
    ]
