# Generated by Django 5.2.8 on 2025-12-27 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('lab', '0002_initial'),
        ('patients', '0002_patientrelationship_relative_and_more'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='lab.equipmentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Analyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_code', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytes', to='lab.equipmentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='lab.sampletype')),
            ],
            bases=('core.service',),
        ),
        migrations.CreateModel(
            name='ExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_requests', to='professionals.professional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='exam_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='lab.examrequest'),
        ),
        migrations.CreateModel(
            name='ExamVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lab.exam')),
            ],
            options={
                'unique_together': {('exam', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ExamField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('decimal', 'Decimal')], default='text', max_length=20)),
                ('formula', models.JSONField(blank=True, null=True)),
                ('classification_rules', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lab.examversion')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_fields', to='lab.measurementunit')),
            ],
            options={
                'unique_together': {('exam_version', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RequestedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_exams', to='lab.examrequest')),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_exams', to='lab.examversion')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_exams', to='lab.sample')),
            ],
            options={
                'unique_together': {('exam_request', 'exam_version')},
            },
        ),
        migrations.CreateModel(
            name='AnalyteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_value', models.TextField()),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab.analyte')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyte_results', to='lab.sample')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab.equipment')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.measurementunit')),
                ('requested_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyte_results', to='lab.requestedexam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='lab.analyte')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyte_codes', to='lab.equipment')),
            ],
            options={
                'unique_together': {('analyte', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='ExamFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('computed_value', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], max_length=20, null=True)),
                ('classification_context', models.JSONField(blank=True, null=True)),
                ('exam_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_results', to='lab.examfield')),
                ('requested_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_results', to='lab.requestedexam')),
            ],
            options={
                'unique_together': {('requested_exam', 'exam_field')},
            },
        ),
        migrations.CreateModel(
            name='ExamFieldTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='lab.examfield')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_links', to='lab.tag')),
            ],
            options={
                'unique_together': {('exam_field', 'tag')},
            },
        ),
    ]
