# Generated by Django 5.2.8 on 2025-12-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_equipmentgroup_measurementunit_tag_equipment_analyte_and_more'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrequest',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examrequest',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examrequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_exam_requests', to='professionals.professional'),
        ),
    ]
