# Generated by Django 5.2.8 on 2025-12-28 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_examrequest_cancel_reason_examrequest_canceled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFieldResultTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_matched', models.JSONField(blank=True, null=True)),
                ('exam_field_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_tags', to='lab.examfieldresult')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_links', to='lab.tag')),
            ],
            options={
                'unique_together': {('exam_field_result', 'tag')},
            },
        ),
    ]
