# Generated by Django 5.2.8 on 2025-12-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0005_examfieldresulttag"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
