# Generated by Django 5.2.8 on 2025-12-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_equipment_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedexam",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
