# Generated by Django 5.2.6 on 2026-03-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_requestedexam_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
