# Generated by Django 5.2.7 on 2025-10-14 05:45

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_relationships', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Relationship',
                'verbose_name_plural': 'Patient Relationships',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('avatar', models.ImageField(blank=True, help_text='Optional profile image', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('address1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_primary_address1', to='core.address')),
                ('address2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary_address2', to='core.address')),
                ('patients', models.ManyToManyField(blank=True, related_name='relatives', through='patients.PatientRelationship', to='patients.patient')),
                ('primary_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_primary_contact', to='core.contact')),
                ('secondary_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary_contact', to='core.contact')),
            ],
            options={
                'verbose_name': 'Relative',
                'verbose_name_plural': 'Relatives',
            },
            bases=('users.user', models.Model),
        ),
        migrations.AddField(
            model_name='patientrelationship',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='patients.relative'),
        ),
        migrations.AlterUniqueTogether(
            name='patientrelationship',
            unique_together={('relative', 'patient')},
        ),
    ]
