# Generated by Django 5.1.6 on 2025-02-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
