# Generated by Django 5.1.6 on 2025-02-20 03:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('doctors', '0003_shift_slot_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shift',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='to_time',
            field=models.TimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('doctor', 'weekday', 'service', 'from_time', 'to_time')},
        ),
    ]
