# Generated by Django 5.1.6 on 2025-02-20 23:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_contact'),
        ('doctors', '0004_alter_shift_unique_together_shift_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_primary_address1', to='core.address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary_address2', to='core.address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_primary_contact', to='core.contact'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='secondary_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary_contact', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
